### ISSUE TITLE
Include link and TL;DR to Capo.js

### ISSUE THREAD

**Issue by McPizza0** [danielroe/nuxt-capo#2]
### 📚 Is your documentation request related to a problem?

I feel that there should be a small explanation about what capo.js does and a link to it https://rviscomi.github.io/capo.js/

When searching online for capo.js, nothing really comes up, and theres no NPM packages.

Something like:

"Capo.js helps analyze the order of elements in your page's <head> section, identifying ways to boost the (perceived) performance of the page."

**Comment by danielroe** [comment]
That would be great! 👌

**Comment by McPizza0** [comment]
Closed by #3
